### The {{ app_name }} Production Configuration Secrets
### Secrets will be merged into Application Configuration
### This files should not be checked into source repos
---

dramatiq:

  ### connection url to rabbitmq server
  rabbitmq_url: amqp://guest:guest@localhost:5672/

#####################################

smtp:

  ### enable authentication for service
  auth: true
  ### auth username
  username: production.user
  ### auth password
  password: top.secret
