### <p><strong>The {{ app_name }} Production Configuration Settings</strong></p>
### - Settings will be merged into Application Configuration.
---



smtp:
  ### SMTP server address to connect for service
  host: production.host.domain
