### <p><strong>The {{ app_name }} Development Configuration Secrets</strong></p>
### - Secrets will be merged into Application Configuration.<br/>
### - This files should not be checked into source repos.
---

dramatiq:

  ### connection url to rabbitmq server
  rabbitmq_url: amqp://guest:guest@localhost:5672/
