### The Cedra Configuration Settings
---

cedra:

### Toggle application level debug (does not toggle framework debugging)
# debug: false

### Where external (third-party) plugins are loaded from
# plugin_dir: /var/lib/cedra/plugins/

### Where all plugin configurations are loaded from
# plugin_config_dir: /etc/cedra/plugins.d/

### Where external templates are loaded from
# template_dir: /var/lib/cedra/templates/

### The log handler label
# log_handler: colorlog

### The output handler label
# output_handler: jinja2

### sample foo option
# foo: bar

rabbitmq:

### connection url to rabbitmq server
# url: amqp://guest:guest@localhost:5672/

worker:
### number of processes to run the dramatiq workers
# processes: 2

### number of threads to run the dramatiq workers
# threads: 1

grpc:

### serve and connect to the grpc service
# url: localhost:50051

### Thread Pool max-workers for grpc service
# worker_threads: 2

log.colorlog:

### Where the log file lives (no log file by default)
# file: null

### The level for which to log.  One of: info, warning, error, fatal, debug
# level: info

### Whether or not to log to console
# to_console: true

### Whether or not to rotate the log file when it reaches `max_bytes`
# rotate: false

### Max size in bytes that a log file can grow until it is rotated.
# max_bytes: 512000

### The maximum number of log files to maintain when rotating
# max_files: 4
