### <p><strong>The Tokeo Development Configuration Settings</strong></p>
### - Settings will be merged into Application Configuration.
---



scheduler:
  ### list of tasks to plan in a crontab style defined by it's key
  tasks:
    ### each entry is defined by its method to call
    count_words_timer:
      ### one or multiple entries in crontab style when to run the task
      crontab: '* * * * *'
