### <p><strong>The Tokeo Testing Configuration Settings</strong></p>
### - Settings will be merged into Application Configuration.
---



test_ext_smtp:
  ### define non secret testing set
  port: 225
  timeout: 30
  tls: true
  auth: true
