### The Tokeo Configuration Settings
---

tokeo:

  ### Toggle application level debug (does not toggle framework debugging)
  # debug: false

  ### Where external (third-party) plugins are loaded from
  # plugin_dir: /var/lib/tokeo/plugins/

  ### Where all plugin configurations are loaded from
  # plugin_config_dir: /etc/tokeo/plugins.d/

  ### Where external templates are loaded from
  # template_dir: /var/lib/tokeo/templates/

#####################################

dramatiq:

  ### module and method to launch dramatiq serve service
  serve: tokeo.main:dramatiq
  ### actors module to launch with services
  actors: tokeo.core.tasks.actors
  ### number of processes to run the dramatiq workers
  worker_processes: 2
  ### number of threads to run the dramatiq workers
  worker_threads: 2
  ### broker to use for backend
  broker: rabbitmq
  ### connection url to rabbitmq server
  rabbitmq_url: amqp://guest:guest@localhost:5672/
  ### mark lock keys by tag
  locks_tag: dramatiq_locks
  ### mark lock keys with prefix
  locks_key_prefix: dq_

#####################################

grpc:

  ### serve and connect to the grpc service
  url: localhost:50051
  ### Thread Pool max-workers for grpc service
  max_worker: 2
  ### module and method to launch grpc server
  proto_add_servicer_to_server: proto.tokeo_pb2_grpc:add_TokeoServicer_to_server
  ### module and servicer for grpc implementations
  grpc_servicer: tokeo.core.grpc.tokeo_servicer:TokeoServicer

#####################################

diskcache:

  ### file path to store permanent data content
  directory: ./tokeo_diskcache
  ### default connection timeout
  timeout: 60
  ### mark lock keys by tag
  locks_tag: diskcache_locks
  ### mark lock keys with prefix
  locks_key_prefix: dc_

#####################################

pocketbase:

  ### connection string to database
  # url: http://localhost:10110

#####################################

smtp:

  ### define one or more standard recipients
  # to: null
  ### define the senders address
  # from_addr: no-reply@example.com
  ### define one or more carbon copy recipients
  # cc: null
  ### define one or more blind copy recipients
  # bcc: null
  ### define a default subject
  # subject: null
  ### define a defeault prefix on subjects
  # subject_prefix: null
  ### SMTP server address to connect for service
  # host: localhost
  ### SMTP port to connect for service
  # port: 25
  ### default timeout when connection will cause an error
  # timeout: 30
  ### enable SSL connection
  # ssl: false
  ### enable TLS on connection, available for SSL and non SSL connections
  # tls: false
  ### enable authentication for service
  # auth: false
  ### auth username
  # username: null
  ### auth password
  # password: null
  ### attach one or more files by default to the messages
  # files: null

#####################################

scheduler:

  ### number of concurrent running tasks overall
  max_concurrent_jobs: 5
  ### the default time zone
  timezone: UTC
  ### list of tasks to plan in a crontab style
  tasks:
      ### each entry is defined by its method to call
    - task: count_word_timer
      ### module where the method is located
      module: tokeo.core.tasks.agents
      ### a name for the entry in schedule list
      name: count-word timer
      ### what to do if multiple run times occur until task starts (earliest, latest, all)
      coalesce: latest
      ### maximum number of seconds the scheduled job’s actual run time is allowed to be late
      misfire_grace_time: null
      ### number of seconds to add to the scheduled time for each job
      delay: null
      ### maximum number of seconds to randomly add to the scheduled time for each job
      max_jitter: null
      ###  maximum number of instances of the task that are allowed to run concurrently
      max_running_jobs: null
      ### one or multiple entries in crontab style when to run the task
      crontab: '*/5 * * * *'
      ### optional arguments send by named args to the method
      kwargs:
        url: https://github.com

#####################################

nicegui:
  ### serve the web service
  host: '127.0.0.1'
  ### port for serving the web service
  port: 8090
  ### main module with pages to serve
  pages: tokeo.core.pages.index
  ### name of default route (/) function
  default: default
  ### web page title
  title: Tokeo NiceGUI
  ### relative filepath or absolute URL to a favicon
  favicon: null
  ### page meta viewport content
  viewport: width=device-width, initial-scale=1
  ### whether to use Quasar's dark mode (True, False, null = Auto)
  dark: null
  ### use tailwindcss
  tailwind: True
  ### secret key for browser-based storage
  storage_secret: null
  ### time between binding updates
  binding_refresh_interval: 0.5
  ### maximum time the server waits for the browser to reconnect
  reconnect_timeout: 5.0
  ### logging level for uvicorn server
  logging_level: warning

#####################################

log.colorlog:

  ### Where the log file lives (no log file by default)
  # file: null

  ### The level for which to log.  One of: info, warning, error, fatal, debug
  # level: info

  ### Whether or not to log to console
  # to_console: true

  ### Whether or not to rotate the log file when it reaches `max_bytes`
  # rotate: false

  ### Max size in bytes that a log file can grow until it is rotated.
  # max_bytes: 512000

  ### The maximum number of log files to maintain when rotating
  # max_files: 4
