### The Tokeo Production Configuration Settings
### Settings will be merged into Application Configuration
---

#####################################

smtp:

  ### SMTP server address to connect for service
  host: production.host.domain
