### <p><strong>The {{ app_name }} Automate Configuration Settings</strong></p>
### - Settings will be merged into Application Configuration.
---



### ### Automation Tasks Configuration
###
### Settings for defining automation tasks that can be run on-demand
automate:
  ### list of hosts reference
  hosts:
    local:
      ### define shell for local tasks
      shell: /bin/sh
  ### list of tasks
  tasks:
    ### optional default settings
    _defaults:
      ### default module for tasks implementations
      module: {{ app_label }}.core.tasks.automate
      ### ensure non overwritable keywords when calling shell commands
      ### options: strict | append | null
      protect: null
      ### ensure to sanitize values and keys before calling shell commands
      sanitize: true
    ### simplest `count_words` task configuration by just an empty dict
    count_words: {}
    ### `uname` task configuration with arguments config
    uname:
      kwargs:
        flags:
          - '-a'
