### <p><strong>The {{ app_name }} NiceGui Configuration Settings</strong></p>
### - Settings will be merged into Application Configuration.
---



### ### NiceGUI Web Interface Configuration
###
### Settings for the NiceGUI web framework and interface behavior
nicegui:
  ### serve the web service
  host: '127.0.0.1'
  ### port for serving the web service
  port: 8080
  ### main module with apis to serve
  apis: {{ app_label }}.site.apis
  ### main module with routes to serve
  routes: {{ app_label }}.site.routes
  ### name of default route (/) function
  default_route: default
  ### web page title
  title: {{ app_name }} Site
  ### relative filepath or absolute URL to a favicon
  favicon: public/favicon.ico
  ### page meta viewport content
  viewport: width=device-width, initial-scale=1
  ### whether to use Quasar's dark mode (True, False, null = Auto)
  dark: null
  ### use tailwindcss
  tailwind: true
  ### use the production version of Vue and Quasar dependencies
  prod_js: true
  ### print your own welcome message on startup
  welcome_message: null
  ### endpoints appear in the autogenerated OpenAPI docs none(=api), page, internal, all
  openapi_documentation: none
  ### enable openapi and specify url
  openapi_url: /_/api/openapi.json
  ### custom openapi ui module for swagger and redoc
  openapi_custom: {{ app_label }}.site.openapi
  ### secret key for browser-based storage
  storage_secret: null
  ### time between binding updates
  binding_refresh_interval: 0.5
  ### maximum time the server waits for the browser to reconnect
  reconnect_timeout: 5.0
  ### root dir to watch for hotload on file changes, null = pages root
  hotload_dir: null
  ### file mask(s) to include for watch
  hotload_includes: '*.py'
  ### file mask(s) to explecitely exclude
  hotload_excludes: '.*, .py[cod], .sw.*, ~*'
  ### logging level for uvicorn server
  logging_level: warning
