### <p><strong>The {{ app_name }} NiceGui Configuration Settings</strong></p>
### - Settings will be merged into Application Configuration.
---



### ### NiceGUI Web Interface Configuration
###
### Settings for the NiceGUI web framework and interface behavior
nicegui:
  ### serve the web service
  host: '127.0.0.1'
  ### port for serving the web service
  port: 8080
  ### module with apis to serve
  apis_module: {{ app_label }}.site.apis
  ### module with routes to serve
  routes_module: {{ app_label }}.site.routes
  ### name of the routes or map method
  routes: routes
  ### web page title
  title: {{ app_name }} Site
  ### relative filepath or absolute URL to a favicon
  favicon: public/favicon.ico
  ### page meta viewport content
  viewport: width=device-width, initial-scale=1
  ### whether to use Quasar's dark mode (True, False, null = Auto)
  dark: null
  ### use tailwindcss
  tailwind: true
  ### use UnoCSS with the specified preset instead of Tailwind CSS
  unocss: null
  ### use the production version of Vue and Quasar dependencies
  prod_js: true
  ### print your own welcome message on startup
  welcome_message: null
  ### custom openapi ui module for openapi, swagger and redoc
  openapi_custom_module: {{ app_label }}.site.openapi
  ### endpoints appear in the autogenerated OpenAPI docs none(=api), page, internal, all
  openapi_documentation: none
  ### enable openapi and specify url
  openapi_url: /_/openapi/openapi.json
  ### enable openapi and swagger url
  openapi_swagger_url: /_/openapi/info
  ### enable openapi and redoc url
  openapi_redoc_url: /_/openapi/docs
  ### secret key for browser-based storage
  storage_secret: null
  ### additional keyword arguments passed to SessionMiddleware
  session_middleware_kwargs: null
  ### time between binding updates
  binding_refresh_interval: 0.5
  ### maximum time the server waits for the browser to reconnect
  reconnect_timeout: 5.0
  ### maximum number of messages that will be stored and resent after a connection interruption (0 to disable)
  message_history_length: 1000
  ### cache control directives for internal static files
  cache_control_directives: public, max-age=31536000, immutable, stale-while-revalidate=31536000
  ### root dir to watch for hotload on file changes, null = pages root
  hotload_dir: null
  ### file mask(s) to include for watch
  hotload_includes: '*.py'
  ### file mask(s) to explecitely exclude
  hotload_excludes: '.*, .py[cod], .sw.*, ~*'
  ### logging level for uvicorn server
  logging_level: warning
  ### optional but preceeding keyword arguments, passed to nicegui.run / uvicorn.run
  run_kwargs: null
