# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/tokeo.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11proto/tokeo.proto\x12\x05tokeo\x1a\x1bgoogle/protobuf/empty.proto" \n\x11\x43ountWordsRequest\x12\x0b\n\x03url\x18\x01 \x01(\t2I\n\x05Tokeo\x12@\n\nCountWords\x12\x18.tokeo.CountWordsRequest\x1a\x16.google.protobuf.Empty"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.tokeo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_COUNTWORDSREQUEST']._serialized_start = 57
    _globals['_COUNTWORDSREQUEST']._serialized_end = 89
    _globals['_TOKEO']._serialized_start = 91
    _globals['_TOKEO']._serialized_end = 164
# @@protoc_insertion_point(module_scope)
